/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

/**
 *
 * @author gerar
 */
public class FrmGanancias extends javax.swing.JFrame {

    /**
     * Creates new form FrmGanancias
     */
    public FrmGanancias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CajaSm = new javax.swing.JTextField();
        CajaIm = new javax.swing.JTextField();
        CajaPrestamos = new javax.swing.JTextField();
        Caja1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CajaTarjeti = new javax.swing.JTextField();
        Caja2 = new javax.swing.JTextField();
        Total = new javax.swing.JButton();
        CajaTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CajaPintura = new javax.swing.JTextField();
        CajaInmueble = new javax.swing.JTextField();
        CajaEquipo = new javax.swing.JTextField();
        Caja3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CajaAgua = new javax.swing.JTextField();
        CajaGas = new javax.swing.JTextField();
        CajaLuz = new javax.swing.JTextField();
        CajaRenta = new javax.swing.JTextField();
        CajaTelefono = new javax.swing.JTextField();
        Caja4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        CajaTrasportePrivado = new javax.swing.JTextField();
        CajaTrasportePublico = new javax.swing.JTextField();
        Caja5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        CajaAlimentos = new javax.swing.JTextField();
        CajaBebidas = new javax.swing.JTextField();
        CajaDesechable = new javax.swing.JTextField();
        Caja6 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        jLabel1.setText("GASTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 110, -1));

        jLabel2.setText("Salario Mensual:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, -1));

        jLabel3.setText("Impuesto Mensual:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, -1));

        jLabel4.setText("Prestamos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, -1));

        jLabel5.setText("Otros:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel1.add(CajaSm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 70, -1));
        jPanel1.add(CajaIm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, -1));
        jPanel1.add(CajaPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 70, -1));
        jPanel1.add(Caja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 70, -1));

        jLabel6.setText("Tarjetitas:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 70, -1));

        jLabel7.setText("Otro:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        CajaTarjeti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaTarjetiActionPerformed(evt);
            }
        });
        jPanel1.add(CajaTarjeti, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 60, -1));
        jPanel1.add(Caja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 60, -1));

        Total.setBackground(new java.awt.Color(255, 102, 102));
        Total.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        Total.setText("TOTAL:");
        Total.setActionCommand("");
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        jPanel1.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        CajaTotal.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        CajaTotal.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(CajaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 110, -1));

        jLabel8.setText("Pintura:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jLabel9.setText("Inmiuebles:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jLabel10.setText("Equipo Computo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 100, -1));

        jLabel11.setText("Otro:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jLabel12.setText("Agua:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));
        jPanel1.add(CajaPintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 50, -1));
        jPanel1.add(CajaInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 50, -1));
        jPanel1.add(CajaEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 50, -1));
        jPanel1.add(Caja3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 50, -1));

        jLabel13.setText("Gas:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        jLabel14.setText("Luz:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        jLabel15.setText("Renta:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, -1, -1));

        jLabel16.setText("Teléfono:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, -1, -1));

        jLabel17.setText("Otro:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, -1, -1));
        jPanel1.add(CajaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 50, -1));
        jPanel1.add(CajaGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 50, -1));
        jPanel1.add(CajaLuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 50, -1));
        jPanel1.add(CajaRenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 50, -1));
        jPanel1.add(CajaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 50, -1));

        Caja4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caja4ActionPerformed(evt);
            }
        });
        jPanel1.add(Caja4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 50, -1));

        jLabel18.setText("Trasporte Privado(Gasolina):");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 170, 10));

        jLabel19.setText("Trasporte Publico(Pasaje):");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 160, -1));

        jLabel20.setText("Otros:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        CajaTrasportePrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaTrasportePrivadoActionPerformed(evt);
            }
        });
        jPanel1.add(CajaTrasportePrivado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 60, -1));
        jPanel1.add(CajaTrasportePublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 60, -1));
        jPanel1.add(Caja5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 60, -1));

        jLabel21.setText("Alimentos:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        jLabel22.setText("Bebidas:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jLabel23.setText("Desechables(Vidrio,Metal,Barro):");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 200, -1));

        jLabel24.setText("Otro:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel25.setText("GASTOS ADMINISTRATIVOS");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, -1));
        jPanel1.add(CajaAlimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 60, -1));
        jPanel1.add(CajaBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 60, -1));
        jPanel1.add(CajaDesechable, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 60, -1));
        jPanel1.add(Caja6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 60, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel26.setText("GASTOS DE MERCADEO");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 140, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel27.setText("GASTOS DE MANTENIMINENTO");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 180, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel28.setText("GASTOS FIJOS");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 90, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel29.setText("GASTOS VARIABLES");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 120, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel30.setText("GASTOS MERCANCIA");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CajaTarjetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaTarjetiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaTarjetiActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
          //Variablres Gastos Administrativos
        float SalarioM,ImpuestoM,Prestamos,Otros1,Total;
        //Gastos de Mercadeo
        float Tarjetitas,Otros2;
        //Gastos de Mantenimiento
        float Pintura,Inmuebles,EquipoComputo,Otros3;
       //Gastos Fijos
        float Agua,Gas,Luz,Renta,Telefono,Otros4;
        //Gastos Variables
        float TrasportePrivado,TrasportePublico,Otros5;
        //Gastos Mercancia
        float Alimentos,Bebidas,Desechables,Otros6;

        

        
        
        //Parsear Gastos Administrativos
        SalarioM=Float.parseFloat(CajaSm.getText());
        ImpuestoM=Float.parseFloat(CajaIm.getText());
        Prestamos=Float.parseFloat(CajaPrestamos.getText());
        Otros1=Float.parseFloat(Caja1.getText());
        //Parsear Gastos de Mercadeo
         Tarjetitas=Float.parseFloat(CajaTarjeti.getText());
         Otros2=Float.parseFloat(Caja2.getText());
         //Parsear Gastos de Manteniminto
         Pintura=Float.parseFloat(CajaPintura.getText());
         Inmuebles=Float.parseFloat(CajaInmueble.getText()); 
         EquipoComputo=Float.parseFloat(CajaEquipo.getText());
         Otros3=Float.parseFloat(Caja3.getText());
        //Parsear Gastos Fijos
         Agua=Float.parseFloat(CajaAgua.getText());
         Gas=Float.parseFloat(CajaGas.getText());
         Luz=Float.parseFloat(CajaLuz.getText());
         Renta=Float.parseFloat(CajaRenta.getText());
         Telefono=Float.parseFloat(CajaTelefono.getText());
         Otros4=Float.parseFloat(Caja4.getText());
         //Parsear Gastos Variables
         TrasportePrivado=Float.parseFloat(CajaTrasportePrivado.getText());
         TrasportePublico=Float.parseFloat(CajaTrasportePublico.getText());
         Otros5=Float.parseFloat(Caja5.getText());
         //Parsear Gastos Mercancia
         Alimentos=Float.parseFloat(CajaAlimentos.getText());
         Bebidas=Float.parseFloat(CajaBebidas.getText());
         Desechables=Float.parseFloat(CajaDesechable.getText());
         Otros6=Float.parseFloat(Caja6.getText());

         
         
        //Operaciones
        Total=SalarioM+ImpuestoM+Prestamos+Otros1+Tarjetitas+Otros2+Pintura+Inmuebles+EquipoComputo+Otros3+Agua+Gas+Luz+Renta+Telefono+Otros4+TrasportePrivado+TrasportePublico+Otros5+Alimentos+Bebidas+Desechables+Otros6;
         
                
    //Mostrara en panatalla el total
    CajaTotal.setText(String.valueOf(Total));
        
    }//GEN-LAST:event_TotalActionPerformed

    private void Caja4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caja4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Caja4ActionPerformed

    private void CajaTrasportePrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaTrasportePrivadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaTrasportePrivadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGanancias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Caja1;
    private javax.swing.JTextField Caja2;
    private javax.swing.JTextField Caja3;
    private javax.swing.JTextField Caja4;
    private javax.swing.JTextField Caja5;
    private javax.swing.JTextField Caja6;
    private javax.swing.JTextField CajaAgua;
    private javax.swing.JTextField CajaAlimentos;
    private javax.swing.JTextField CajaBebidas;
    private javax.swing.JTextField CajaDesechable;
    private javax.swing.JTextField CajaEquipo;
    private javax.swing.JTextField CajaGas;
    private javax.swing.JTextField CajaIm;
    private javax.swing.JTextField CajaInmueble;
    private javax.swing.JTextField CajaLuz;
    private javax.swing.JTextField CajaPintura;
    private javax.swing.JTextField CajaPrestamos;
    private javax.swing.JTextField CajaRenta;
    private javax.swing.JTextField CajaSm;
    private javax.swing.JTextField CajaTarjeti;
    private javax.swing.JTextField CajaTelefono;
    private javax.swing.JTextField CajaTotal;
    private javax.swing.JTextField CajaTrasportePrivado;
    private javax.swing.JTextField CajaTrasportePublico;
    private javax.swing.JButton Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
